baseURL = 'https://metaross.github.io/'
languageCode = 'en-us'
title = 'Michael C Ross'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false
  description = "Builder of AI things"

[menu]
[[menu.before]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.after]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/oneross"
  weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
